//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 新一代CaptB点名器.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("新一代CaptB点名器.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 点名 的本地化字符串。
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string button3_Text {
            get {
                return ResourceManager.GetString("button3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPoint模式 的本地化字符串。
        /// </summary>
        internal static string button4_Text {
            get {
                return ResourceManager.GetString("button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取名单时发生错误 的本地化字符串。
        /// </summary>
        internal static string CErrTitle {
            get {
                return ResourceManager.GetString("CErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string Content_Text {
            get {
                return ResourceManager.GetString("Content.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除名单时发生错误 的本地化字符串。
        /// </summary>
        internal static string DelErrTitle {
            get {
                return ResourceManager.GetString("DelErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功删除名单！ 的本地化字符串。
        /// </summary>
        internal static string DelToastContent {
            get {
                return ResourceManager.GetString("DelToastContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DelToastTitle {
            get {
                return ResourceManager.GetString("DelToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否退出CaptB点名器？退出后将重置名单点名状态 的本地化字符串。
        /// </summary>
        internal static string ExitContent {
            get {
                return ResourceManager.GetString("ExitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出确认 的本地化字符串。
        /// </summary>
        internal static string ExitCTitle {
            get {
                return ResourceManager.GetString("ExitCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出CaptB点名器时发生错误 的本地化字符串。
        /// </summary>
        internal static string ExitErrTitle {
            get {
                return ResourceManager.GetString("ExitErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新导入名单可能会解决此问题。 的本地化字符串。
        /// </summary>
        internal static string ExRe_ReImport {
            get {
                return ResourceManager.GetString("ExRe_ReImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新安装CaptB点名器可能会解决此问题。 的本地化字符串。
        /// </summary>
        internal static string ExRe_Reinstall {
            get {
                return ResourceManager.GetString("ExRe_Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新导入名单或重新安装CaptB点名器可能会解决此问题。 的本地化字符串。
        /// </summary>
        internal static string ExRe_RR {
            get {
                return ResourceManager.GetString("ExRe_RR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CaptB点名器 的本地化字符串。
        /// </summary>
        internal static string Form1_Text {
            get {
                return ResourceManager.GetString("Form1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_0068 {
            get {
                object obj = ResourceManager.GetObject("Icon_0068", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_0096 {
            get {
                object obj = ResourceManager.GetObject("Icon_0096", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_0248 {
            get {
                object obj = ResourceManager.GetObject("Icon_0248", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_0378 {
            get {
                object obj = ResourceManager.GetObject("Icon_0378", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon_1016 {
            get {
                object obj = ResourceManager.GetObject("Icon_1016", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_1657 {
            get {
                object obj = ResourceManager.GetObject("Icon_1657", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_27081 {
            get {
                object obj = ResourceManager.GetObject("Icon_27081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_3995 {
            get {
                object obj = ResourceManager.GetObject("Icon_3995", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_5059 {
            get {
                object obj = ResourceManager.GetObject("Icon_5059", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_5060 {
            get {
                object obj = ResourceManager.GetObject("Icon_5060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon_5299 {
            get {
                object obj = ResourceManager.GetObject("Icon_5299", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_5350 {
            get {
                object obj = ResourceManager.GetObject("Icon_5350", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon_7566 {
            get {
                object obj = ResourceManager.GetObject("Icon_7566", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_9752 {
            get {
                object obj = ResourceManager.GetObject("Icon_9752", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_9905 {
            get {
                object obj = ResourceManager.GetObject("Icon_9905", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon_99051 {
            get {
                object obj = ResourceManager.GetObject("Icon_99051", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_9916 {
            get {
                object obj = ResourceManager.GetObject("Icon_9916", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_9922 {
            get {
                object obj = ResourceManager.GetObject("Icon_9922", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon_99221 {
            get {
                object obj = ResourceManager.GetObject("Icon_99221", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_9948 {
            get {
                object obj = ResourceManager.GetObject("Icon_9948", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_9960 {
            get {
                object obj = ResourceManager.GetObject("Icon_9960", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon_99601 {
            get {
                object obj = ResourceManager.GetObject("Icon_99601", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 导入名单时发生错误 的本地化字符串。
        /// </summary>
        internal static string ImportErrTitle {
            get {
                return ResourceManager.GetString("ImportErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功导入名单！ 的本地化字符串。
        /// </summary>
        internal static string ImportToastContent {
            get {
                return ResourceManager.GetString("ImportToastContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功 的本地化字符串。
        /// </summary>
        internal static string ImportToastTitle {
            get {
                return ResourceManager.GetString("ImportToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总人数： 的本地化字符串。
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menuStrip1 的本地化字符串。
        /// </summary>
        internal static string menuStrip1_Text {
            get {
                return ResourceManager.GetString("menuStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入名单 的本地化字符串。
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无剩余人名，检查首选项设置是否正确或重置名单状态可能会解决此问题。点击”确定“将会重置名单状态。 的本地化字符串。
        /// </summary>
        internal static string OverflowContent {
            get {
                return ResourceManager.GetString("OverflowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点名失败 的本地化字符串。
        /// </summary>
        internal static string OverflowTitle {
            get {
                return ResourceManager.GetString("OverflowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置失败 的本地化字符串。
        /// </summary>
        internal static string ResetErrTitle {
            get {
                return ResourceManager.GetString("ResetErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功重置名单状态！ 的本地化字符串。
        /// </summary>
        internal static string ResetToastContent {
            get {
                return ResourceManager.GetString("ResetToastContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置成功 的本地化字符串。
        /// </summary>
        internal static string ResetToastTitle {
            get {
                return ResourceManager.GetString("ResetToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出名单时发生错误 的本地化字符串。
        /// </summary>
        internal static string SaveErrTitle {
            get {
                return ResourceManager.GetString("SaveErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出名单 的本地化字符串。
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功导出名单！ 的本地化字符串。
        /// </summary>
        internal static string SaveToastContent {
            get {
                return ResourceManager.GetString("SaveToastContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功 的本地化字符串。
        /// </summary>
        internal static string SaveToastTitle {
            get {
                return ResourceManager.GetString("SaveToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时发生错误 的本地化字符串。
        /// </summary>
        internal static string StartupErrTitle {
            get {
                return ResourceManager.GetString("StartupErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人 的本地化字符串。
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新时发生错误 的本地化字符串。
        /// </summary>
        internal static string UpdateErrToastTitle {
            get {
                return ResourceManager.GetString("UpdateErrToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入门 的本地化字符串。
        /// </summary>
        internal static string 入门GToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("入门GToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于CaptB点名器 的本地化字符串。
        /// </summary>
        internal static string 关于CaptB点名器ToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("关于CaptB点名器ToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送反馈 的本地化字符串。
        /// </summary>
        internal static string 发送反馈FToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("发送反馈FToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整名单 的本地化字符串。
        /// </summary>
        internal static string 完整名单ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("完整名单ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入名单 的本地化字符串。
        /// </summary>
        internal static string 导入名单AToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("导入名单AToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出名单 的本地化字符串。
        /// </summary>
        internal static string 导出名单CToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("导出名单CToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string 帮助HToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("帮助HToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议功能 的本地化字符串。
        /// </summary>
        internal static string 建议功能LToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("建议功能LToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技术支持 的本地化字符串。
        /// </summary>
        internal static string 技术支持TToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("技术支持TToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告问题 的本地化字符串。
        /// </summary>
        internal static string 报告问题ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("报告问题ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string 文件ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("文件ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增功能 的本地化字符串。
        /// </summary>
        internal static string 新增功能WToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("新增功能WToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未点名单 的本地化字符串。
        /// </summary>
        internal static string 未点名单ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("未点名单ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string 查看ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("查看ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        internal static string 检查更新LToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("检查更新LToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑名单 的本地化字符串。
        /// </summary>
        internal static string 编辑名单BToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("编辑名单BToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出CaptB点名器 的本地化字符串。
        /// </summary>
        internal static string 退出CaptB点名器ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("退出CaptB点名器ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐私政策 的本地化字符串。
        /// </summary>
        internal static string 隐私政策PToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("隐私政策PToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首选项 的本地化字符串。
        /// </summary>
        internal static string 首选项PToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("首选项PToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
